### PR TITLE
feat: wallet_deploymentData

### PR DESCRIPTION
**Pull request by janek26**

### CODE REVIEW

**Review by leo-starkware — APPROVED** [review]
Looks good to me. I would possibly add a comment on sigdata that you would always return an empty string

**Review by leo-starkware — COMMENTED** [review]
There should also be a Cairo version field

**Review by diegodelrieu — APPROVED** [review]

**Comment by dan-ziv** [comment]
@janek26, before we proceed with the merge, could you please address the following issues:

* The `wallet_deploymentData` call has the potential to return `null`. 
* The `version` field is returned from the request. Therefore, it should be included in the type definition.

Thank you for looking into these matters.

**Comment by avimak** [comment]
@dan-ziv pls check #194 which also covers for this request (and is already merged)

**Comment by avimak** [comment]
@janek26 perhaps we could close this one, now that https://github.com/starknet-io/get-starknet/pull/194 has been merged

**Comment by dan-ziv** [comment]
https://github.com/starknet-io/get-starknet/pull/194 Already covered this PR.

**Pull request closed without merging**
