### PR TITLE
feat: add argentX download url of edge

### PR DESCRIPTION
**Pull request by YanYuanFE**

### CODE REVIEW

**Comment by avimak** [comment]
@janek26 / @dhruvkelawala  could u pls review?

**Comment by lazarmitic** [comment]
Any updates on this? Our users on edge browser are having isses, and this PR will fix the problem.

**Comment by avimak** [comment]
> Any updates on this? Our users on edge browser are having isses, and this PR will fix the problem.

hey, are you on the argent team? I asked @janek26 or @dhruvkelawala to approve this PR 🙏

**Review by janek26 — APPROVED** [review]

**Comment by YanYuanFE** [comment]
thanks

**Comment by lazarmitic** [comment]
thanks guys!

**Pull request merged**
