### PR TITLE
feat: support keplr wallet

### PR DESCRIPTION
**Pull request by delivan**

### CODE REVIEW

**Comment by fracek** [comment]
Hello, changes look good. Can you fix the formatting issue and then I'll merge it.

**Comment by avimak** [comment]
> Hello, changes look good. Can you fix the formatting issue and then I'll merge it.

@fracek @delivan perhaps I'm missing something, but I didn't see any Starknet support in this wallet..

**Comment by delivan** [comment]
@avimak Do we need the implementation to be deployed to production to merge this PR? We are still working on it.

**Comment by avimak** [comment]
> @avimak Do we need the implementation to be deployed to production to merge this PR? We are still working on it.

Yes, otherwise dapps will display it to users, and if they choose keplr, they'll be unable to use it, leading to potential user churn, which ultimately harms the dapps.

**Comment by delivan** [comment]
@fracek @avimak We deployed Starknet support to production now. Please consider this PR can be merged.

**Comment by fracek** [comment]
Hey @delivan , the change looks good now that the wallet is available. Please fix the tests/ci and we're good to merge.

**Comment by delivan** [comment]
I missed this. Can you check again? @fracek

**Comment by fracek** [comment]
Thanks!

**Pull request merged**
