### PR TITLE
feat: implement metamask starknet snap

### PR DESCRIPTION
**Pull request by stanleyyconsensys**
**Description**:
the PR is to add metamask starknet snap as a wallet options on the get-starknet UI and return a compilable wallet object to  get-starknet as well as the other wallets

the concept is same with the other PR: #195 

**Concept**:
Due to MetaMask limitation, the SNAP itself can not directly inject a object into window instance, and snap itself is communicated via JSONRPC, SNAP can only return JSON-serializable response
https://docs.metamask.io/snaps/reference/rpc-api/

Hence we create a wallet object in get-starknet codebase, the object itself will setup as a bridge to communicate with SNAP via JSONRPC
We then runtime inject this object into get-starknet
image

**Detail implementation** 
- create a class object named `MetaMaskSnap` to communicate with the snap via the window ethereum provider
- create a class object named `MetaMaskAccount` to extend the `Account` class from starknet package, and overriding execute, signMessage, declare with `MetaMaskSnap`
- create a class object named `MetaMaskSigner` to implement the `SignerInterface` interface from starknet package, and implement all member methods with `MetaMaskSnap`
- create a class object named `MetaMaskSnapWallet` to implement the same API as `IStarknetWindowObject`
  -   when `enable` method trigger, it will request user to install starknet snap into metamask if not installed
- inject `MetaMaskSnapWallet` when `getAvailableWallets, getPreAuthorizedWallets, getDiscoveryWallets, getLastConnectedWallet `method are consuming 
- enhance example page to demo the integration

### CODE REVIEW

**Comment by naorye2** [comment]
@stanleyyconsensys 
It seems that you add the snap implementation into get-starknet code.
starknet_metamask should be injected from the snap itself.

**Comment by stanleyyconsensys** [comment]
> hould be injected from the snap itself.

hi @naorye2 thanks for the review
there is no way to injected from the snap like other wallet
such as
return a account object or injected the account object into window object

as snap is a JS script that run on metamask, it act like a serverless API, hence, the script itself cant inject anything
Plus
snap can be only communicate via rpc, means the snap will be able to return any non hashable response (such as account object)

**Comment by naorye2** [comment]
@stanleyyconsensys got it. I suggest the following:
1. Your wallet implementation must be hosted on your behalf so you eventually will provide a url for a script.
2. get-starknet will hold a reference to that script (under discovery.js).
3. get-starket will check whether metamask loaded with snaps support (the code that you added under MetaMaskSnap.GetProvider) and if it is, it will load the script of yours.
4. From that point, starknet_metamask will be injected by your script.

WDYT?

**Comment by stanleyyconsensys** [comment]
> account object or injected the

@naorye2 

thank you for the advice
it is a good idea
but may i ask how about get-starknet adding a npm package from us, in that way, user does not required to load our jS via internet on the fly, instead, it compile together with get-starknet

the major different is, when we using async load script, there may be some issue from user ENV, may blocking the access of the script

with npm package, get-starknet would just need to maintain the version of our package, but it may also create a dependency on us 

how does it sound like to you?

**Comment by naorye2** [comment]
@stanleyyconsensys 
This is sounds like a better solution :)
However, this package will be bundled along the build process into a separate file that will be imported dynamically according to metamask existence and snap support.

**Comment by naorye2** [comment]
@stanleyyconsensys 
I am working on a PR for metamask starknet brisge as we spoke.
Currently I am using the logic you wrote but than I realized that this logic is missing async loading of metamask (in case metamask loads minute after get-starkent, we will miss it).
I saw that approach: https://github.com/MetaMask/detect-provider
Is it good enough for metamask detection (than we will use `provider && hasSnapSupport(provider)`)?

**Comment by naorye2** [comment]
@stanleyyconsensys 
https://github.com/starknet-io/get-starknet/pull/208

**Comment by stanleyyconsensys** [comment]
@naorye2 , the detectEthereumProvider can be useful if the client browser only install metamask, 

but in some edge case, if the user has installed some wallets which overrided the Ethereum object, it will lead to using the wrong provider 

i would suggest you can combine both way to inject the provider, may i ask where will you inject the bootstrapMetamaskBridge?

**Comment by naorye2** [comment]
@stanleyyconsensys 

According to `@metamask/detect-provider`, it verifies whether it is metamask.
image

Can you review my implementation?

`bootstrapMetamaskBridge` is called in `packages/core/src/main.ts` in `getStarknet()` function.

**Comment by stanleyyconsensys** [comment]
i think you can try that way first, and i will test it by enabling Phantom and coinbase wallet later

**Comment by stanleyyconsensys** [comment]
@naorye2 here is the consensys package for supporting get-starknet,
https://www.npmjs.com/package/@consensys/get-starknet

 it is a dev version
we will release a stable version once the test is success

**Comment by naorye2** [comment]
@stanleyyconsensys 
I integrated your package (dev version for the meanwhile).
Can you expose `MetaMaskProvider`?

Please review my PR https://github.com/starknet-io/get-starknet/pull/208.

**Comment by stanleyyconsensys** [comment]
Sure, let me export all the type and component for you

**Comment by naorye2** [comment]
Handled here https://github.com/starknet-io/get-starknet/pull/208

**Pull request closed without merging**
